synthetic-package: false
arb-dir: l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
untranslated-messages-file: untranslated_strings.txt
output-dir: lib/src/generated/l10n