gen:
	dart-dbus generate-remote-object kf5_org.kde.JobView.xml -o ../lib/src/dbus/job_view.g.dart
	dart-dbus generate-remote-object kf5_org.kde.JobViewServer.xml -o ../lib/src/dbus/job_view_server.g.dart